### ISSUE TITLE
Mono Issue

### ISSUE THREAD

**Issue by pythonpete32** [pythonpete32/hive-template#19]
# TODO 
- [ ] redesterID function
- [x] A1 Apps
- [ ] OE apps
   - [ ] Projects
   - [ ] Allocations
   - [x] Address Book
   - [x] Dot Voting
- [ ] Permissions
   - [ ] create YAML file
   - [ ] create permissions map
   - [ ] add to template
